version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/var-dumper
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/dom-crawler
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
